name: Node-RED
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 9
paginate_path: "/blog/page/:num/"
url: https://nodered.org
plugins:
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-polyglot
future: true
authors:
    nick:
        display_name: Nick O'Leary
        url: https://twitter.com/knolleary
languages: ["en", "zh-CN"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true